name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci-checks:
    name: Code Integration Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install React Dependencies
        run: |
          cd frontend/job_board
          npm install

      - name: Run ESLint for React
        run: |
          
          npx eslint . --ext .js,.jsx,.ts,.tsx || true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Django Dependencies
        run: |
          cd tech-stack-proposal
          pip install -r requirements.txt

      - name: Run Flake8 for Django
        run: |
          cd tech-stack-proposal
          flake8 . || true

      - name: Test Docker Compose Build
        run: |
          docker-compose -f docker-compose.yml up --build -d
          sleep 5
          docker-compose ps
          docker-compose down
