# Generated by Django 4.2.19 on 2025-02-07 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='Student',
        ),
    ]
