name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci-checks:
    name: Code Integration Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  

      - name: Start Docker Containers
        run: |
          docker compose up --build -d
          sleep 10

      - name: Check Logs for Issues
        run: |
          docker compose logs --tail=50

      - name: Stop Containers After Check
        run: docker compose down

  deploy:
    name: Deploy Application on EC2
    runs-on: self-hosted
    needs: ci-checks  # Deploy only if 'ci-checks' succeeds

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Stop Existing Containers
        run: |
          docker compose down || true  # Stop any running containers if they exist

      - name: Build and Start Docker Compose
        run: |
          docker compose up -d --build  # Build and run the application in detached mode
