name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci-checks:
    name: Code Integration Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  
        
      - name: Start Docker Containers
        run: |
          docker compose up --build -d
          sleep 10
      #     docker ps

      - name: Check Logs for Issues
        run: |
          docker compose logs --tail=50

      # - name: Stop Containers After Check
      #   run: docker compose down